### ISSUE TITLE
Error undefined method 'create' for ModelName:Class

### ISSUE THREAD

**Issue by conradwt** [amberframework/granite#233]
After creating a model, migrating the database, I'm seeing the following issue:

```
$ amber db seed
Error in db/seeds.cr:7: undefined method 'create' for Person:Class

me = Person.create(first_name: "Steven", last_name: "Luscher", email: "steveluscher@fb.com", username: "steveluscher")
            ^~~~~~


12:03:55 Database   | (INFO) Seeded database
```

seeds.cr:
```crystal
require "../config/application.cr"

# reset DB
Person.clear

# create people
bsmith = Person.create(first_name: "Bob", last_name: "Smith", email: "bob.smith@example.com", username: "bsmith")
```

person.cr:
```crystal
class Person < Granite::ORM::Base
  adapter pg
  table_name people

  # id : Int64 primary key is created for you
  field first_name : String
  field last_name : String
  field email : String
  field username : String
  timestamps
end
```

**Comment by faustinoaq** [comment]
Hi @conradwt What granite version are you using?

**Comment by faustinoaq** [comment]
I can reproduce this issue: amber v0.7.2 and granite_orm (legacy) v0.8.4

```
➜  app01 nano db/seeds.cr
➜  app01 amber db seed   
Error in db/seeds.cr:7: undefined method 'create' for Person:Class

bsmith = Person.create(first_name: "Bob", last_name: "Smith", email: "bob.smith@example.com", username: "bsmith")
                ^~~~~~


02:39:39 Database   | (INFO) Seeded database
```

**Comment by faustinoaq** [comment]
Works fine on granite_orm (legacy) v0.9.1

```
Installing granite_orm (0.9.1)
Using quartz_mailer (0.5.1)
Using email (0.2.5)
Using jasper_helpers (0.2.0)
Using garnet_spec (0.1.1)
Using selenium (0.3.0)
➜  app01 amber db seed   
relation "people" does not exist (PQ::PQError)
  from lib/pg/src/pq/connection.cr:192:7 in 'handle_error'
  from lib/pg/src/pq/connection.cr:0:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:151:7 in 'read'
  from lib/pg/src/pq/connection.cr:146:7 in 'read'
  from lib/pg/src/pq/connection.cr:289:31 in 'expect_frame'
  from lib/pg/src/pq/connection.cr:288:5 in 'expect_frame'
  from lib/pg/src/pg/statement.cr:18:5 in 'perform_query'
  from lib/pg/src/pg/statement.cr:35:14 in 'perform_exec'
  from lib/db/src/db/statement.cr:97:14 in 'perform_exec_and_release'
  from lib/db/src/db/statement.cr:67:7 in 'exec'
  from lib/db/src/db/pool_statement.cr:14:30 in 'exec'
  from lib/db/src/db/query_methods.cr:263:7 in 'exec'
  from lib/granite_orm/src/adapter/pg.cr:15:7 in 'clear'
  from lib/granite_orm/src/granite_orm/querying.cr:41:5 in 'clear'
  from db/seeds.cr:4:1 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:101:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:135:3 in 'main'
  from __libc_start_main
  from _start
  from ???
02:44:34 Database   | (INFO) Seeded database
➜  app01 amber db create migrate
database "app01_development" already exists
➜  app01 amber db migrate       
02:44:53 Database   | (INFO) Migrating db, current version: 0, target: 20180618023526395
02:44:53 Database   | (INFO) OK   20180618023526395_create_person.sql
➜  app01 amber db seed          
02:45:01 Database   | (INFO) Seeded database
➜  app01 amber exec 'People.all'
Error in line 2: while requiring "./tmp/1529307911618_console.cr"

in tmp/1529307911618_console.cr:2: undefined constant People

  People.all
  ^~~~~~

➜  app01 amber exec 'Person.all'
02:45:32 Granite    | (INFO) SELECT "people"."id", "people"."first_name", "people"."last_name", "people"."email", "people"."username", "people"."created_at", "people"."updated_at" FROM "people" : []
[#<Person:0x55c84fae9a00 @new_record=false, @destroyed=false, @errors=[], @id=1_i64, @first_name="Bob", @last_name="Smith", @email="bob.smith@example.com", @username="bsmith", @created_at=2018-06-18 07:45:01 UTC, @updated_at=2018-06-18 07:45:01 UTC>]
```

Try to update your `granite_orm` dependency version to `0.9.1`in your `shard.yml`

```yml
  granite_orm:
    github: amberframework/granite-orm
    version: ~> 0.9.0
```

**Comment by conradwt** [comment]
@faustinoaq After upgrading `granite_orm` to 0.9.0, things are now working as expected.

**Comment by Blacksmoke16** [comment]
I'm going to close this since you figured it out.  Any other issues create a new issue.
